services:
  grist:
    image: gristlabs/grist:1.7
    ports:
      - "8484:8484"
    environment:
      - GRIST_WIDGET_LIST_URL=${GRIST_WIDGET_LIST_URL:-http://host.docker.internal:5173/manifest.json}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - grist_data:/persist

volumes:
  grist_data: